name: Build my Angular App

on:
 push:
   branches: [ main ]

jobs:
  build-Angular-app:
     runs-on: ubuntu-latest
     
     steps:
       - uses: actions/checkout@v6-beta
       - name: Set Up Node JS
         uses: actions/setup-node@v6.0.0
         with:
           node-version: 22.x

       - name: instal Dependiency
         run: npm install
       - name: build anhular App   
         run: npm run build
       
       
       
       
